### PR TITLE
Fix issue #28. Rewrite the program with SOLID

### PR DESCRIPTION
**Pull request by Mskat**
The rule is The Interface Segregation Principle

### CODE REVIEW

**Comment by mohayemin** [comment]
Thanks for submitting a solution. Please note that we do not accept commits in the master branch. Please review the [Submit Solutions](https://github.com/iut-cse/oo-kata#submit-solutions) section in the README and commit accordingly.

Feel free to ask for help if needed. Thanks.

**Comment by Mskat** [comment]
Hi @mohayemin, I don't understand how I can push changes to your repo without forking it before. I don't have access to push changes to your repo. In the other hand, when I do a pull request, I can only compare to your master or other people's branches. Thanks:)

**Comment by mohayemin** [comment]
Hi @Mskat 
Please see if you can do the followings steps.
* Clone the repository in your machine  
  ```git clone https://github.com/iut-cse/oo-kata```
* Create a branch with your GitHub username.   
  ```git branch Mskat```
* Create a folder int the `/solutions` folder with your GitHub username. Your folder should be `/solutions/Mskat`.
* Write any code in that folder
* PUSH ONLY TO YOUR BRANCH. Pull requests to the master branch will not be reviewed.
* Mention the issue number in your commit. For example, a commit is for solving issue 1, mention #1 somewhere in the commit. It will be linked to the problem automatically.

Thanks for contributing by the way. I did not realize that you are not a member of the community. Welcome!

**Comment by Mskat** [comment]
Thanks @mohayemin:)
I've done all the steps, I think. I didn't do a pull request, do you see my branch now?

**Pull request closed without merging**
